- improve ipmi check, chassis status exited with 0 if /dev/ipmi0 existed but pointed to wrong device (like gdth driver) - LC_ALL=C to avoid localized output side effects - version 1.14
Changed files:
    check_ipmi -> 1.14
    nagios-plugin-check_ipmi.spec -> 1.16

diff --git a/check_ipmi b/check_ipmi
--- a/check_ipmi
+++ b/check_ipmi
@@ -86,10 +86,11 @@ ignored_status() {
 
 # checks if ipmitool is even usable on this system
 check_ipmitool() {
-	echo "Checking for IPMI..."
-	$ipmitool chassis status >/dev/null 2>&1
-	if [ $? != 0 ]; then
-		echo "Chassis status failed, modprobing"
+	local status
+	echo "IPMI chassis selftest..."
+	status=$(LC_ALL=C $ipmitool chassis selftest 2>/dev/null | awk '/Self Test Results/{print $NF}')
+	if [ "$status" != "passed" ]; then
+		echo "Chassis selftest failed, modprobing"
 		$modprobe ipmi_si
 		if [ $? != 0 ]; then
 			echo "ERROR: ipmi_si module did not load, probably IPMI not present"
@@ -102,13 +103,13 @@ check_ipmitool() {
 			exit 1
 		fi
 	else
-		echo "Seems OK"
+		echo "OK: $status"
 		return
 	fi
 
 	# check again, maybe static dev needs device updating
-	$ipmitool chassis status >/dev/null 2>&1
-	if [ $? != 0 ]; then
+	status=$(LC_ALL=C $ipmitool chassis selftest 2>/dev/null | awk '/Self Test Results/{print $NF}')
+	if [ "$status" != "passed" ]; then
 		echo "Still fails, checking ipmi /dev node"
 		major=$(awk '$2 == "ipmidev" {print $1}' /proc/devices)
 		if [ -z "$major" ]; then
@@ -120,8 +121,8 @@ check_ipmitool() {
 		mknod $dev c $major 0
 	fi
 
-	$ipmitool chassis status >/dev/null 2>&1
-	if [ $? != 0 ]; then
+	status=$(LC_ALL=C $ipmitool chassis selftest 2>/dev/null | awk '/Self Test Results/{print $NF}')
+	if [ "$status" != "passed" ]; then
 		echo "ERROR: Can't get it to work, I give up"
 		exit 1
 	fi
@@ -216,7 +217,7 @@ if [ ! -s "$cache_filename" ]; then
 fi
 
 t=$(mktemp) || die CRITICAL "Can't create tempfile"
-$sudo $ipmitool -S $cache_filename sdr > $t || die CRITICAL "Can't run ipmitool sdr"
+LC_ALL=C $sudo $ipmitool -S $cache_filename sdr > $t || die CRITICAL "Can't run ipmitool sdr"
 # VRD 1 Temp       | 34 degrees C      | ok
 # CMOS Battery     | 3.12 Volts        | ok
 # VCORE            | 0x01              | ok
